
#Spring-Config
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${RDS_URL}/product_db
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    jpa:
      show-sql: true

#Server port declaration
server:
  port: ${SERVER_PORT}


#Discovery-Config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    instance:
      ferIpAddress: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL}
    healthcheck:
      enabled: true
